#pragma once
/* ##  GENERAL COMMANDS  ## */
#define PLAYER_CMD_START 0x7E
#define PLAYER_NO_FEEDBACK 0x00
#define PLAYER_VERSION 0xFF
#define PLAYER_CMD_END 0xEF 
#define PLAYER_DT_LEN 0x06

#define PLAYER_TX_CMD_START uart_tx(PLAYER_CMD_START); \
	uart_tx(PLAYER_VERSION); \
	uart_tx(PLAYER_DT_LEN); \

/* ##  PAUSE COMMAND  ## */
#define PLAYER_PAUSE 0x0E
#define PLAYER_PAUSE_CHECKSUM_HI 0xFE 
#define PLAYER_PAUSE_CHECKSUM_LO 0xED

/* ##  PLAY COMMAND ## */
#define PLAYER_PLAY 0x0D
#define PLAYER_PLAY_CHECKSUM_HI 0xFE
#define PLAYER_PLAY_CHECKSUM_LO 0xEE

/* ##  RESET COMMAND  ## */
#define PLAYER_RESET 0x0C
#define PLAYER_RESET_CHECKSUM_HI 0xFE
#define PLAYER_RESET_CHECKSUM_LO 0xEF

/* ##  NEXT COMMAND  # */
#define PLAYER_NEXT 0x01
#define PLAYER_NEXT_CHECKSUM_HI 0xFE
#define PLAYER_NEXT_CHECKSUM_LO 0xFA

/* ## VOLUME SET COMMAND  ## */
#define PLAYER_VOLUME_SET 0x06

/* ## SET EQ COMMAND  ## */
#define PLAYER_EQ_SET 0x07

/**/
#define PLAYER_SELECT_SD 0x09
#define PLAYER_SELECT_SD_ARG 0x02
#define PLAYER_SELECT_SD_CHECKSUM_HI 0xFE
#define PLAYER_SELECT_SD_CHECKSUM_LO 0xF0
